### ISSUE TITLE
git-pr에서 URL이 잘못 만들어지는 경우 수정

### ISSUE THREAD

**Issue by nungnung** [8percent/github-flow-sugar#6]
git config --get remote.origin.url의 결과에 따라서, github.com부분이 중복되어서 pull request 페이지를 열어줄 url이 잘못 생성되는 경우가 있는 듯합니다. git-pr 명령어 사용시 Not found 페이지가 뜨는 경우가 있었습니다.

eg.
git config --get remote.origin.url
=> https://github.com/8percent/github-flow-sugar.git

결과
https://github.com///github.com/8percent/github-flow-sugar/compare/...

이런 경우를 위해서 GITHUB_ID에서 github.com가 남아있는 경우 삭제하도록 수정하면 좋을듯합니다.

**Comment by ghost** [comment]
제가 수정했는데, pr 권한이 막혀있는 것 같습니다.
